LANGUAGE_MAPPING = {
    "ar": "Arabic",
    "bg": "Bulgarian",
    "de": "German",
    "el": "Greek",
    "en": "English",
    "et": "Estonian",
    "es": "Spanish",
    "fa": "Persian",
    "fr": "French",
    "fi": "Finnish",
    "hi": "Hindi",
    "hu": "Hungarian",
    "it": "Italian",
    "ka": "Georgian",
    "ko": "Korean",
    "pl": "Polish",
    "pt": "Portuguese",
    "ro": "Romanian",
    "ru": "Russian",
    "sv": "Swedish",
    "th": "Thai",
    "tr": "Turkish",
    "uk": "Ukrainian",
    "vi": "Vietnamese",
    "zh": "Chinese"
}